### ISSUE TITLE
Question | AWS Payment

### ISSUE THREAD

**Issue by aldinoed** [ardikabs/praktisi-mengajar-logbook#4]
Apakah payment jenius dan bank jago sudah tidak disupport AWS ya pak? Karena saya mencoba pay menggunakan jenius selalu gagal

**Comment by ardikabs** [comment]
halo @aldinoed , sepertinya harus pakai yg jenis kartu kredit, belum pernah coba juga untuk pemakaian debit di AWS ya

**Comment by aldinoed** [comment]
Jadi harus pakai yg kartu kredit ya pak. Untuk pemakaian debit di AWS masih belum pernah pak
